version = 1

[*]
; ctx-size = 32768
n-predict = 4096
threads = 16
parallel = 1
n-gpu-layers = 99
flash-attn = auto
cache-type-k = q8_0
cache-type-v = q8_0
jinja = true
metrics = true
sleep-idle-seconds = 300
temp = 0.7
top-p = 1.0
min-p = 0.01

[Qwen3.5-9B-MTP]
hf-repo = unsloth/Qwen3.5-9B-MTP-GGUF:UD-Q4_K_XL
load-on-startup = false
spec-type = draft-mtp
spec-draft-n-max = 2
spec-draft-p-min = 0.80

[Qwen3.6-27B-MTP]
hf-repo = unsloth/Qwen3.6-27B-MTP-GGUF:UD-Q4_K_XL
load-on-startup = false
spec-type = draft-mtp
spec-draft-n-max = 2
spec-draft-p-min = 0.80

[gemma4-26B]
hf-repo = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_M
load-on-startup = false
